runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'

    - run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ~/.npm
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
