name: Dependabot Auto Merge
on:
  pull_request_target:
    types: [labeled, edited]

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    name: Dependabot Auto Merge
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - run: yarn lint

  merge:
    needs: test
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: merge
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
