name: Test CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Cache multiple paths
        uses: pat-s/always-upload-cache@v2
        id: yarn-cache
        with:
          path: |
            ~/.npm
            ~/cache
            !~/cache/exclude
            **/node_modules
            .umi
          key: npm-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: lint
        run: yarn lint
