name: Test CI
on: [push, pull_request]

jobs:
  precheck:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/docs/**"]'

  test:
    name: Code quality check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Cache multiple paths
        uses: ktmud/cached-dependencies@v1
        id: yarn-cache
        with:
          run: cache-restore yarn

      - run: echo "${{ steps.yarn-cache.outputs.cache-hit }}"

      - name: Install
        uses: ktmud/cached-dependencies@v1
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        with:
          run: |
            yarn
            cache-save yarn

      - name: Generate Temp
        run: yarn postinstall

      - name: lint
        run: yarn lint
