name: Test CI
on: [push, pull_request]

jobs:
  test:
    name: Code quality check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install
        run: yarn

      - name: lint
        run: yarn lint
