name: Test CI
on: [push, pull_request]

jobs:
  test:
    name: Code quality check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: pnpm install

      - name: lint
        run: pnpm run lint
